<?php
declare(strict_types=1);

/**
 * Texte des CGU de la version 1, utilise une seule fois pour amorcer la table CguVersion.
 * Ensuite le texte vit en base et se modifie depuis le back-office (module CGU).
 *
 * Jetons remplaces a l'affichage par les reglages de la plateforme, pour que le texte suive les tarifs :
 *   {{cancel_fee}} {{revision_timeout}} {{strike_threshold}} {{strike_window}} {{cancel_grace}}
 *
 * A FAIRE RELIRE par un conseil juridique camerounais avant la mise en production.
 */
return [
    'fr' => [
        ['num' => '1', 'title' => 'Service', 'body' => "KoliGo met en relation vendeurs, livreurs et clients pour la livraison de colis dans les villes couvertes par la plateforme. La plateforme prélève une commission sur chaque livraison confirmée par code de réception ; son taux est affiché dans l'application."],
        ['num' => '2', 'title' => 'Paiements', 'body' => "Les paiements sont opérés via MTN MoMo et Orange Money. La répartition est automatique entre le vendeur, le livreur et la plateforme dès la confirmation de réception. Les frais d'annulation et les remboursements sont régis par l'article 9."],
        ['num' => '3', 'title' => 'Données & KYC', 'body' => "Les vendeurs et livreurs fournissent une pièce d'identité (CNI) et un selfie pour vérification. Un seul dossier est valable pour les deux rôles. Ces données sont conservées de façon sécurisée et utilisées uniquement pour la conformité réglementaire."],
        ['num' => '4', 'title' => 'Responsabilités', 'body' => "KoliGo agit en tant que plateforme intermédiaire. Le vendeur est responsable du conditionnement des colis et de l'exactitude du gabarit déclaré. Le livreur est responsable de la bonne prise en charge et de la livraison dans les délais annoncés."],
        ['num' => '5', 'title' => 'Résiliation', 'body' => "Tout utilisateur peut supprimer son compte à tout moment depuis les paramètres. KoliGo se réserve le droit de suspendre un compte en cas de fraude, d'abus ou de non-respect des CGU."],
        ['num' => '6', 'title' => 'Droit applicable', 'body' => "Les présentes conditions sont régies par le droit camerounais. Tout litige sera soumis aux juridictions compétentes de Douala, Cameroun."],
        ['num' => '7', 'title' => 'Déclaration du colis et calcul du prix', 'body' => "7.1 Le vendeur choisit, au moment de la publication, la catégorie de taille (« gabarit ») qui correspond à son colis, indique sa nature et joint une photo du colis emballé.\n7.2 Le prix de la livraison est calculé par KoliGo à partir de la région, de la distance, du gabarit choisi et du type de livreur. Il est affiché au vendeur avant la publication.\n7.3 Le vendeur déclare des informations exactes : le gabarit choisi doit correspondre à la taille et à l'encombrement réels du colis."],
        ['num' => '8', 'title' => 'Contrôle à la collecte et révision du prix', 'body' => "8.1 À son arrivée, avant la remise du code de collecte, le livreur vérifie que le colis correspond au gabarit déclaré.\n8.2 S'il constate un écart, le livreur propose un autre gabarit en joignant une photo. Le vendeur voit le nouveau prix dans l'application.\n8.3 Le vendeur dispose de {{revision_timeout}} minutes pour accepter ou refuser. Passé ce délai, la course est annulée sans frais pour le vendeur.\n8.4 Si le colis part sans correction, le gabarit déclaré est définitif : le livreur ne peut plus réclamer de supplément.\n8.5 En cas de désaccord, le vendeur peut contester la correction auprès du support KoliGo, qui décide au vu des photos du vendeur et du livreur."],
        ['num' => '9', 'title' => "Frais d'annulation et remboursement", 'body' => "9.1 Si le vendeur refuse le prix révisé, la course est annulée et le vendeur doit au livreur des frais d'annulation de {{cancel_fee}} F CFA. Ce montant est indiqué sur l'écran de publication.\n9.2 Les frais d'annulation sont versés intégralement au livreur et débités du portefeuille du vendeur ; si le solde est insuffisant, le solde est mis à zéro et la différence est déduite de ses prochains versements.\n9.3 Le vendeur qui annule une course dont le livreur est déjà en route, plus de {{cancel_grace}} minutes après son acceptation, doit les mêmes frais. L'annulation d'une course non encore acceptée est gratuite.\n9.4 Aucun frais n'est dû lorsque l'annulation est décidée par le livreur ou par KoliGo, ou lorsque le support juge la correction injustifiée.\n9.5 Lorsque le vendeur a payé le transport d'avance et que la course est annulée, il est remboursé immédiatement sur son portefeuille KoliGo, diminué des frais d'annulation uniquement si l'annulation lui est imputable. Il peut ensuite retirer ce montant.\n9.6 Chaque débit ou remboursement apparaît dans l'historique du vendeur avec son motif."],
        ['num' => '10', 'title' => 'Contrôle renforcé', 'body' => "10.1 Après {{strike_threshold}} écarts confirmés en {{strike_window}} jours, le vendeur est placé en contrôle renforcé : le colis est pesé à la collecte et le transport est payé d'avance.\n10.2 Le vendeur est informé de ce changement dans l'application.\n10.3 Un écart annulé par le support ne compte pas."],
        ['num' => '11', 'title' => 'Objets interdits et surveillance des échanges', 'body' => "11.1 Il est interdit de faire transporter par KoliGo des stupéfiants, des armes et munitions, des explosifs, des produits toxiques ou dangereux, de faux billets ou faux documents, des espèces protégées (ivoire, pangolin, etc.) ou tout autre objet dont la détention ou le transport est illégal au Cameroun.
11.2 Le livreur peut refuser tout colis qu'il juge suspect ou dangereux ; le vendeur reste seul responsable du contenu qu'il déclare.
11.3 Pour la sécurité de tous, KoliGo peut consulter les messages échangés dans le cadre d'une livraison et les analyser automatiquement afin de repérer les échanges portant sur des produits interdits.
11.4 En cas de soupçon, KoliGo peut suspendre ou bloquer le compte concerné, retenir les sommes en cours et transmettre les informations utiles aux autorités compétentes."],
        ['num' => '12', 'title' => 'Modification des conditions', 'body' => "12.1 KoliGo peut modifier les présentes conditions. Les utilisateurs doivent accepter la nouvelle version avant leur prochaine publication ou leur prochaine course.\n12.2 KoliGo conserve la version acceptée et la date d'acceptation de chaque utilisateur."],
    ],
    'en' => [
        ['num' => '1', 'title' => 'Service', 'body' => "KoliGo connects sellers, couriers and customers for parcel delivery in the cities covered by the platform. The platform takes a commission on each delivery confirmed by reception code; the rate is shown in the app."],
        ['num' => '2', 'title' => 'Payments', 'body' => "Payments are made through MTN MoMo and Orange Money. The split between seller, courier and platform is automatic once reception is confirmed. Cancellation fees and refunds are governed by article 9."],
        ['num' => '3', 'title' => 'Data & KYC', 'body' => "Sellers and couriers provide an ID document (CNI) and a selfie for verification. A single file is valid for both roles. This data is stored securely and used only for regulatory compliance."],
        ['num' => '4', 'title' => 'Responsibilities', 'body' => "KoliGo acts as an intermediary platform. The seller is responsible for packaging and for the accuracy of the declared size. The courier is responsible for proper pickup and delivery within the announced time."],
        ['num' => '5', 'title' => 'Termination', 'body' => "Any user may delete their account at any time from the settings. KoliGo may suspend an account in case of fraud, abuse or breach of these terms."],
        ['num' => '6', 'title' => 'Governing law', 'body' => "These terms are governed by Cameroonian law. Any dispute will be brought before the competent courts of Douala, Cameroon."],
        ['num' => '7', 'title' => 'Parcel declaration and price', 'body' => "7.1 When publishing, the seller picks the size category (\"size\") matching the parcel, states what it is, and attaches a photo of the packed parcel.\n7.2 The delivery price is calculated by KoliGo from the region, the distance, the chosen size and the courier type. It is shown to the seller before publication.\n7.3 The seller declares accurate information: the chosen size must match the real size and bulk of the parcel."],
        ['num' => '8', 'title' => 'Pickup check and price revision', 'body' => "8.1 On arrival, before the pickup code is entered, the courier checks that the parcel matches the declared size.\n8.2 If there is a mismatch, the courier proposes another size and attaches a photo. The seller sees the new price in the app.\n8.3 The seller has {{revision_timeout}} minutes to accept or refuse. After that, the delivery is cancelled at no cost to the seller.\n8.4 If the parcel leaves without a correction, the declared size is final: the courier can no longer claim a supplement.\n8.5 In case of disagreement, the seller may dispute the correction with KoliGo support, which decides on the seller's and courier's photos."],
        ['num' => '9', 'title' => 'Cancellation fees and refunds', 'body' => "9.1 If the seller refuses the revised price, the delivery is cancelled and the seller owes the courier a cancellation fee of {{cancel_fee}} XAF. This amount is shown on the publishing screen.\n9.2 The cancellation fee is paid in full to the courier and debited from the seller's wallet; if the balance is insufficient, it is set to zero and the difference is deducted from future payouts.\n9.3 A seller who cancels a delivery whose courier is already on the way, more than {{cancel_grace}} minutes after acceptance, owes the same fee. Cancelling a delivery that has not yet been accepted is free.\n9.4 No fee is due when the cancellation is decided by the courier or by KoliGo, or when support finds the correction unjustified.\n9.5 When the seller prepaid the transport and the delivery is cancelled, they are refunded immediately to their KoliGo wallet, minus the cancellation fee only if the cancellation is attributable to them. They can then withdraw that amount.\n9.6 Each debit or refund appears in the seller's history with its reason."],
        ['num' => '10', 'title' => 'Enhanced control', 'body' => "10.1 After {{strike_threshold}} confirmed mismatches within {{strike_window}} days, the seller is placed under enhanced control: the parcel is weighed at pickup and transport is paid in advance.\n10.2 The seller is informed of this change in the app.\n10.3 A mismatch cancelled by support does not count."],
        ['num' => '11', 'title' => 'Prohibited items and monitoring of messages', 'body' => "11.1 It is forbidden to have KoliGo carry narcotics, weapons and ammunition, explosives, toxic or dangerous goods, counterfeit money or forged documents, protected species (ivory, pangolin, etc.) or any other item whose possession or transport is illegal in Cameroon.
11.2 The courier may refuse any parcel they consider suspicious or dangerous; the seller alone is responsible for the contents they declare.
11.3 For everyone's safety, KoliGo may read the messages exchanged during a delivery and analyse them automatically to detect exchanges about prohibited goods.
11.4 In case of suspicion, KoliGo may suspend or block the account concerned, hold pending funds and pass relevant information to the competent authorities."],
        ['num' => '12', 'title' => 'Changes to these terms', 'body' => "12.1 KoliGo may change these terms. Users must accept the new version before their next publication or delivery.\n12.2 KoliGo keeps the version accepted and the acceptance date for each user."],
    ],
];
